apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

bases:
  - github.com/argoproj/argo-cd/manifests/crds?ref=v2.5.2
  - github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=v2.5.2
  - github.com/argoproj/argo-cd/manifests/base?ref=v2.5.2

resources:
  - resources/namespace.yaml

patchesStrategicMerge:
  - patches/argocd-cm.yaml
  - patches/argocd-server-deployment.yaml
  - patches/argocd-repo-server-deployment.yaml
  - patches/argocd-application-controller-statefulset.yaml